# This workflow will install Python dependencies and render the notebook to html
name: Render notebook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter
    - name: Render notebook
      run: |
        jupyter nbconvert a_star_study.ipynb --to html --output a_star_study.html
        
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Gabriel Nativel-Fontaine
        author_email: gabriel.nativelfontaine@gmail.com
        message: "Updated notebook render :genie:"
        add: "*.html"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
